WebShop/Models/Page.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebShop.Models
{
    public class Page
    {
        public int Id { get; set; } // this is going to be automatically recognized as the primary key
        [Required] // to make the column not nullable in the db
        //[Display(Name = "Fruit")] // it will be displayed in the view if we have a @Html.DsiplayNameFor method used
        [MinLength(2, ErrorMessage = "Minimum length is 2")] // custom error message
        public string Title { get; set; }
        [Required]
        public string Slug { get; set; }
        [Required, MinLength(4, ErrorMessage = "Minimum length is 4")] // it is possible to add more than one attributes in one line
        public string Content { get; set; }
        public int Sorting { get; set; }
    }
}

WebShop/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebShop.Infrastructure;

namespace WebShop.Models
{
    public class SeedData
    {
        /// <summary>
        /// If there is no page entries in the DB, create them.
        /// </summary>
        /// <param name="serviceProvider"></param>
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using var context = new WebShopContext(serviceProvider.GetRequiredService<DbContextOptions<WebShopContext>>());
            
            // if there is no pages in the DB create them
            if (context.Pages.Any())
                return;

            context.Pages.AddRange(
                new Page
                {
                    Title = "Home",
                    Slug = "home",
                    Content = "home page",
                    Sorting = 0
                },
                new Page
                {
                    Title = "About Us",
                    Slug = "about-us",
                    Content = "about us page",
                    Sorting = 100
                },
                new Page
                {
                    Title = "Serivces",
                    Slug = "services",
                    Content = "services page",
                    Sorting = 100
                },
                new Page
                {
                    Title = "Contact",
                    Slug = "contact",
                    Content = "contact page",
                    Sorting = 100
                });

            context.SaveChanges();
        }
    }
}

WebShop/Areas/Admin/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebShop.Infrastructure;
using WebShop.Models;

namespace WebShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PagesController : Controller
    {
        readonly WebShopContext _context;

        public PagesController(WebShopContext context)
        {
            _context = context;
        }

        // IActionResult can return more on less anything
        // if you want to be more specific use for example IRedirectResult
        // GET /admin/pages
        public async Task<IActionResult> Index()
        {
            IQueryable<Page> pages = from p in _context.Pages orderby p.Sorting select p;
            List<Page> pageList = await pages.ToListAsync();

            // we do not specify the view name here so by default it will look for the View with the method name which is "Index" in this case
            return View(pageList);
        }

        // GET /admin/pages/details/6
        public async Task<IActionResult> Details(int id)
        {
            Page page = await _context.Pages.FirstOrDefaultAsync(x => x.Id == id);
            if(page == null)
                return NotFound();

            return View(page);
        }

        // GET /admin/pages/create
        public IActionResult Create() => View();

        // POST /admin/pages/details/6
        [HttpPost] // if we don't specify the request attribute it is GET by default
        public async Task<IActionResult> Create(Page page)
        {
            // model binding - it is a way to pass data to methods
            if(ModelState.IsValid)
            {
                page.Slug = page.Title.ToLower().Replace(" ", "-");
                page.Sorting = 100;

                var slug = await _context.Pages.FirstOrDefaultAsync(x => x.Slug == page.Slug);
                if(slug != null)
                {
                    ModelState.AddModelError("", "The title already exists.");
                    return View(page);
                }

                _context.Add(page);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View(page);
        }
    }
}

WebShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<!-- this is main layout file, all smaller views are injected into this one -->

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="/" target="_blank">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Pages" asp-action="Index">Pages</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-- here is where smaller views are injected in the action method -->
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<!-- this is main layout file, all smaller views are injected into this one -->

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-- here is where smaller views are injected in the action method -->
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WebShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>